### DISCUSSION TITLE
Dynamic list of configs

### DISCUSSION THREAD

**Discussion by reinhard-brandstaedter** [Dynatrace/dynatrace-configuration-as-code#1463] [Ideas]
I was looking into following scenario, and tried to approach it maybe with GO templating, but it seems thats not the right way.

I want to apply a configuration that is scoped to a single HOST to a long/dynamic list of hosts. E.g. if I want to use monaco to switch the monitoring mode of many hosts I'd need a ```config.yaml``` that contains a long list of individual configs:

```
configs:
- id: monitoring_mode_host_123
  config:
    template: monitoring_mode.json
    skip: false
  type:
    settings:
      schema: builtin:host.monitoring.mode
      schemaVersion: "1.3"
      scope: HOST-123
- id: monitoring_mode_host_456
  config:
    template: monitoring_mode.json
    skip: false
  type:
    settings:
      schema: builtin:host.monitoring.mode
      schemaVersion: "1.3"
      scope: HOST-456
```

and a monitoring_mode.json:
```
{"monitoringMode": "INFRA_ONLY"}
```

Is there any way that one could supply this list of hosts in a dynamic fashion built in to monaco? or does one have to create the config.yaml with each and every host in question?
