### DISCUSSION TITLE
Creating Web Applications with pre-defined IDs

### DISCUSSION THREAD

**Discussion by reinhard-brandstaedter** [Dynatrace/dynatrace-configuration-as-code#1527] [Ideas]
As far as I saw monaco 2.0 is unable to create Web applications with predefined custom APPLICATION-IDs.
I cannot create a config that would look like this:
```
configs:
- id: my_custom_application
  config:
    parameters:
      identifier: APPLICATION-AAAAA00000000001
    name: my_application
    template: webshop-application-templ.json
    skip: false
  type:
    api: application-web
```
and in the template use something like this:
```
{
  "identifier": "{{.identifier}}",
  "name": "{{.name}}"
  "conversionGoals": [],
  ...
}

Monaco will only use a PUT command against the API and not a POST request which would allow to create an application with a custom IP. Which would it make possible to easily transport the same configuration between environments.

Also due to the lack of pre-defining the APPLICATION-ID I also cannot create application detection rules together with Applications, unless I'm missing something?
How would one create application detection rules if applications do not exist yet, or their ID is unknown.

So my Idea would be to have a feature if a config type of api:application-web contains a ID that monaco would POST the config and so we could use the referenced ID also in a application detection rule.
