### DISCUSSION TITLE
Cross-Project config references?

### DISCUSSION THREAD

**Discussion by reinhard-brandstaedter** [Dynatrace/dynatrace-configuration-as-code#1550] [Q&A] [answered]
Hello,
I'm trying to figure out how/if cross-project references could work. Assume I have this project layout:

manifest.yaml
```
manifestVersion: 1.0

projects:
- name: managementzones
  path: managementzones
- name: alertingprofile
  path: alertingprofile
```

Now if I want to create a config for an alerting profile that references the management zone (id), how would I do that?
A config.yaml for the alerting profile like this wouldn't work:
```
configs:
- id: alerting_stocklevel
  config:
    parameters:
      managementzone_id:
        configId: stocklevel
        configType: builtin:management-zones
        property: id
        type: reference
    template: alerting_stocklevel.json
    skip: false
  type:
    settings:
      schema: builtin:alerting.profile
      schemaVersion: "8.5"
      scope: environment
```

The reference would only work "locally" in the alertingprofile project:
```
warn    configuration "alertingprofile:builtin:alerting.profile:alerting_stocklevel" references unknown configuration "alertingprofile:builtin:management-zones:stocklevel"
```

Do I need to restructure the whole project, using 1 global project of type grouping like this:

```
manifestVersion: 1.0

projects:
- name: global
   path: global
   type: grouping
```

Or is there another way?
