### DISCUSSION TITLE
Templating with gomplate - short references must have between 1 and 4 elements

### DISCUSSION THREAD

**Discussion by reinhard-brandstaedter** [Dynatrace/dynatrace-configuration-as-code#1602] [Q&A] [answered]
I tried using an array to template a json config (iterate and recerate a setting), however monaco complains that the array is too long?

in my config.yaml:
```
configs:
- id: srg_suggest_search
  config:
    parameters:
      rail: xxxlutz
      locales: ["cs_cz", "de_ch", "hr_hr", "hu_hu", "ro_ro", "rs_rs", "sv_se", "si_si", "sk_sk"]
    template: srg_suggest_search.json
    skip: false
  type:
    settings:
      schema: app:dynatrace.site.reliability.guardian:guardians
      schemaVersion: "1.3.1"
      scope: environment
```

When running monaco deply I get this error:
```
 error   locales: cannot parse parameter definition in `services/discover/config.yaml`: short references must have between 1 and 4 elements. you provided `9`
```
What is the reason behind this limit?

kr,
Reinhard

**Comment by reinhard-brandstaedter** [comment, marked as answer]
Answer to myself:
One must use this format to define a array variable:
```
parameters:
      locales: 
        type: value
        value: ["cs_cz", "de_ch", "hr_hr", "hu_hu", "ro_ro", "rs_rs", "sv_se", "si_si", "sk_sk"]
```
this seems to work
