### DISCUSSION TITLE
Nested variable rendering when using file-type parameters

### DISCUSSION THREAD

**Discussion by reinhard-brandstaedter** [Dynatrace/dynatrace-configuration-as-code#1607] [Q&A]
Hello,
I'm trying to make my config better readable as having DQL queries directly in JSON templates is really badly human readable.
So I have moved from having DQL in json like this (long complex newline/escaped string):
```
    {
      "name": "Check for Ingest Indices",
      "description": "When Ingest Indices are present instead of aliases, this means that something went wrong during the data ingestion process",
      "objectiveType": "DQL",
      "dqlQuery": "fetch bizevents\n| filter event.type == \"SuggestSearchService-Report\"\n| filter rail == \"{{ .rail }}\"\n| limit 1\n| parse report, \"JSON:json\"\n| fieldsKeep event, json, timestamp\n| fieldsFlatten json\n| fieldsAdd indicesWithIngest = json.indicesWithIngest\n| expand indicesWithIngest\n| filter isNotNull(indicesWithIngest)\n| summarize count = count()\n| fieldsAdd count=if(isNull(count),0,else: count)",
      "comparisonOperator": "LESS_THAN_OR_EQUAL",
      "target": 0.0
    }
```
to externalizing it via a single file, referenced in the config.yaml:
```
configs:
- id: srg_suggest_search
    parameters:
      rail: webshop
      locales: 
        type: value
        value: 
          - cs_cz
          - de_ch
          - hr_hr
      check_for_ingest_indices:
        type: file
        path: dql/check_for_ingest_indices.dql
        references:
          - rail
```

This works fine. First I even did with a compound type and have the DQL inline in the config.yaml. I can then reference the DQL in the json template like this, which is much cleaner:
```
{
      "name": "Check for Ingest Indices",
      "description": "When Ingest Indices are present instead of aliases, this means that something went wrong during the data ingestion process",
      "objectiveType": "DQL",
      "dqlQuery": "{{ .check_for_ingest_indices }}",
      "comparisonOperator": "LESS_THAN_OR_EQUAL",
      "target": 0.0
    }
```

However now comes the tricky part. When I want to use a template iteration in the json template that should replace a placeholder in the  DQL file content (which wasn't replaced by the initial parameter rendering, this doesn't work:

```
{{- range .locales }}
    {
      "name": "Check for indices - locale: {{ . }}",
      "description": "This objective checks if the number of documents indexed has significantly fallen",
      "objectiveType": "DQL",
      "dqlQuery": "{{ $.check_for_ingest_indices }}",
      "comparisonOperator": "GREATER_THAN_OR_EQUAL",
      "autoAdaptiveThresholdEnabled": true
    }
{{- end }}
```
This is rendered into an objective for every locale in the list, but the content of the file (which also contains placeholders like "{{ . }}") is not rendered anymore.
I know go template doesn't support nested placeholders, but has anyone found a workaround for this usecase?

**Comment by Laubi** [comment]
Hi @reinhard-brandstaedter, I was not able to reproduce your issue, but I made a small change to the loop you're using, adding commas to the JSON array using `{{if $index}},{{end}}`.

I am using the following setup: 
<details><summary>template.yaml</summary>

```
{
  "name" : "Test",
  "description" : "My description",
  "tags" : [ ],
  "variables" : [ ],
  "objectives" : [
    {{- range $index, $element :=  .locales }}
    {{if $index}},{{end}}
    {
      "name": "Check for indices - locale: {{ . }}",
      "description": "This objective checks if the number of documents indexed has significantly fallen",
      "objectiveType": "DQL",
      "dqlQuery": "{{ $.check_for_ingest_indices }}",
      "comparisonOperator": "GREATER_THAN_OR_EQUAL",
      "autoAdaptiveThresholdEnabled": true
    }
    {{- end }}
  ]
}
```

</details>
<details><summary>config.yaml</summary>

```
configs:
- id: guardian
  type:
    settings:
      schema: app:dynatrace.site.reliability.guardian:guardians
      scope: tenant
  config:
    template: template.json
    parameters:
      rail: webshop
      locales:
        type: value
        value:
        - en
        - de
      check_for_ingest_indices:
        type: file
        path: dql.txt
        references:
        - rail

```

</details>
<details><summary>dql.txt</summary>

```
fetch bizevents
| filter event.type == "SuggestSearchService-Report"
| filter rail == "{{ .rail }}"
| limit 1
| parse report, "JSON:json"
| fieldsKeep event, json, timestamp
| fieldsFlatten json
| fieldsAdd indicesWithIngest = json.indicesWithIngest
| expand indicesWithIngest
| filter isNotNull(indicesWithIngest)
| summarize count = count()
| fieldsAdd count=if(isNull(count),0,else: count)
```

</details>


This results in the following SRGs:
![image](https://github.com/user-attachments/assets/590641b8-9c99-484b-bccf-b9c66d0a5dc6)


Could you please provide a reproducible sample of the issue you are facing so that we can investigate further?
