### DISCUSSION TITLE
Proposal - More generic names for environment properties

### DISCUSSION THREAD

**Discussion by rszulgo** [Dynatrace/dynatrace-configuration-as-code#186] [Ideas]
I plan to add a support for Dynatrace Managed and Cluster configuration and permission REST API. Therefore, I'd like to reuse "environments" concept as it is now with an addition to specify a "cluster environment". For example:

```yaml
cluster.production-cluster:
  - name: "prod-cluster"
  - env-url: "{{ .Env.CLUSTER_PROD }}"
  - env-token-name: "TOKEN_SERVICE_PROVIDER_API"
  - type: "cluster"
production.environment1:
  - name: "environment1"
  - env-url: "{{ .Env.URL_ENVIRONMENT_1 }}"
  - env-token-name: "TOKEN_ENVIRONMENT_1"
```

As you see in the example above, existing environment property names could be more intuitive. I'm proposing to change property names, by adding new ones, and deprecating existing ones as following:

- `env-url` to `url`
- `env-token-name` to `token`
- new property `type` with a value `cluster` to differentiate environment types. If skipped then by default it's "environment" type.

What do you think?
