### DISCUSSION TITLE
Delete flag for configuration

### DISCUSSION THREAD

**Discussion by kristofre** [Dynatrace/dynatrace-configuration-as-code#218] [Ideas]
Similar to the skipDeployment flag, it would be great to have a delete flag that you can use to delete config.

This would allow us to make deletion project-specific, and by using environment-specific configuration, you can choose to delete it from specific environments:

```
config:
    - app-one: "application.json"
  
app-one.staging:
    - name: "app-one"
    - uemPercentage: "75"

app-one.production:
    - name: "app-one"
    - uemPercentage: "75"
    - delete: "true"
```
