### DISCUSSION TITLE
--specific-environment flag and env vars

### DISCUSSION THREAD

**Discussion by ghost** [Dynatrace/dynatrace-configuration-as-code#350] [Archive] [answered]
Hi community,

Given that I have the following `environments.yaml` file:

```
sprint:
    - name: "sprint"
    - env-url: "{{ .Env.DT_SPRINT_URL }}"
    - env-token-name: "DT_SPRINT_TOKEN"
    
acl:
  - name: "acl"
  - env-url: "{{ .Env.ACL_URL }}"
  - env-token-name: "ACL_TOKEN"
```

I want to push configuration only to my `acl` environment so I do this:

```
export ACL_URL=***
export ACL_TOKEN=***
monaco --environments=environments.yaml --specific-environment=acl
```

Monaco errors because I haven't defined env vars for the `sprint` environment. Logically though, I don't want to set those as I don't care about that when using the `--specific-environment` flag.

In other words, monaco should only read the relevant `environments.yaml` file when `--specific-environment` flag is used.
