### DISCUSSION TITLE
How to use templates?

### DISCUSSION THREAD

**Discussion by joostvz** [Dynatrace/dynatrace-configuration-as-code#385] [Q&A]
We have one SaaS environment for Dynatrace, which in the future will contain separate management zones, one per customer. And each customer/management zone will contain several hosts, synthetic monitors, metrics, etc. As these configs will be almost identical for each of our customers, it sounds like a good plan to create a single template for it, and use that template for all our individual customers. Most of the configuration will be similar, except for the entity names which will contain the name of the customer. Also, we need to have the possibility to configure overrides for a specific customer, like a specific alert threshold.

But how should we create this in Monaco? Something like this perhaps:

    projects
        _template
            anomaly-detection-metrics
            synthetic-monitor
                monitor_a.json
                monitor_b.json
                synthetic-monitor.yaml
        Customer_1
        Customer_2
Where _Customer_1_ and _Customer_2_ refer to the templated json files in the __template_ folder? In this case, do we have to create the two synthetic monitors in the separate customer folders as well, with a reference to the templated json files? Or is there a way to automatically include the two monitors for each customer project?

Or is it better to define different environments per customer, instead of different projects? Even though we only have one Dynatrace environment?

Any advice is highly appreciated!

**Comment by tatomir146** [comment]
Hi @joostvz, if I get you correctly, as you are deploying only one env, there is no actual need to split config in separate projects. You can still use only one but use one and same JSON multiple times by just parametrising it, e.g.

```
config:
  - customer1-config: "template.json"
  - customer2-config: "template.json"
  
 customer1-config:
   - name: "My customer 1 config"
   - param1: "customer 1"
   - param2: "another param"
  
  customer2-config:
   - name: "My customer 2 config"
   - param1: "customer 2"
   - param2: "another param for customer 2" 
```

So you end up having 1 json but reusing it multiple times and just customising it for the customer by changing params.
