### DISCUSSION TITLE
Specific configuration per environment or group

### DISCUSSION THREAD

**Discussion by PatMis16** [Dynatrace/dynatrace-configuration-as-code#699] [Q&A]
Can sombody explain how this exactly works: https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/configuration/yaml_config
I would like to use Monaco to create HTTP monitors with different requests. Currenly it is not really dynamic because requests can not be added dynamicaly. 

I wondered if I could do someting like that to add multiple requests to a HTTP monitor via Monaco:

```yaml
---
config:
  - Probe_myService: "probe-text-content-template.json"

Probe_myService:
 - name: "My_Local_Services"
 - description: "Dumy-Description-for-Request"
 - url: "<generic url for a request>"
 - supportgroup: "BETR-SYSMGMT"
 - frequency: "10"
 - enabled: "false"
 - locations: '"locations": ["SYNTHETIC_LOCATION-XXXXXXXXXXXXX"]'
 - probetag: "internalprobing"
 - content: "Healthy"
 - servicetime: "Servicetime_Level5"

Probe_myService.request
 - description: "Request 1"
 - url: "<URL for Request 1>"
 - content: "Healthy"

Probe_myService.request
 - description: "Request 2"
 - url: "<URL for Request 2>"
 - content: "Healthy"

Probe_myService.request
 - description: "Request 3"
 - url: "<URL for Request 3>"
 - content: "Healthy"
```

The JSON-Template would look like this:

```json
{
  "name": "{{ .name }}",
  "frequencyMin": "{{ .frequency }}",
  "enabled": "{{ .enabled }}",
  "type": "HTTP",
  "createdFrom": "GUI",
  "script": {
    "version": "1.0",
    "requests": [
      {
        "description": "{{ .description }}",
        "url": "{{ .url }}",
        "method": "GET",
        "validation": {
          "rules": [
            {
              "value": "{{ .content }}",
              "passIfFound": true,
              "type": "patternConstraint"
            },
            {
              "value": "30",
              "passIfFound": false,
              "type": "certificateExpiryDateConstraint"
            }
          ],
          "rulesChaining": "or"
        },
        "configuration": {
          "acceptAnyCertificate": true,
          "followRedirects": true
        }
      }
    ]
  },
  {{ .locations }},
  "anomalyDetection": {
    "outageHandling": {
      "globalOutage": true,
      "localOutage": false,
      "localOutagePolicy": {
        "affectedLocations": null,
        "consecutiveRuns": null
      }
    },
    "loadingTimeThresholds": {
      "enabled": true,
      "thresholds": [
        {
          "type": "TOTAL",
          "valueMs": 6000
        }
      ]
    }
  },
  "tags": [
    {
      "source": "USER",
      "context": "CONTEXTLESS",
      "key": "servicetime",
      "value": "{{ .servicetime }}"
    },
    {
      "source": "USER",
      "context": "CONTEXTLESS",
      "key": "SSL_check"
    },
    {
      "source": "USER",
      "context": "CONTEXTLESS",
      "key": "probing",
      "value": "{{ .probetag }}"
    },
    {
      "source": "USER",
      "context": "CONTEXTLESS",
      "key": "obm_supportgroup",
      "value": "{{ .supportgroup }}"
    }
  ],
  "managementZones": [],
  "automaticallyAssignedApps": [],
  "manuallyAssignedApps": [],
  "requests": [
  ]
}
```

I think I am on the wrong path. Any ideas? Thank you!
