### ISSUE TITLE
Validate that all config properties are used in template

### ISSUE THREAD

**Issue by patrickpichler** [Dynatrace/dynatrace-configuration-as-code#23]
It is quite easy by copy and paste pull create configs which have properties that are not used.

E.g.

```yaml
dashboard:
  - name: "test"
  - testTicket: "hello"
```

```json
{
  "name": {{ .name }}
}
```
When running dry run, it would be nice to point out that `testTicket` is unused.
