### ISSUE TITLE
Documentation - monaco 2.0

### ISSUE THREAD

**Issue by tatomir146** [Dynatrace/dynatrace-configuration-as-code#354]
Make sure all new features are well documented and covered by enough examples.

**Comment by tatomir146** [comment]
@kristofre we can consider to include the examples you mentioned today with this ticket?

**Comment by tatomir146** [comment]
Overriding complex values could not be done partially. 

e.g. this kind of override will remove `.complexThreshold.unit` from the `complexThreshold` object:
```
parameters:
  threshold: 15
  complexThreshold:
    type: value
    value:
      amount: 15
      unit: sec

groupOverrides:
  - group: development
    override:
      parameters:
        complexThreshold:
          type: value
          value:
            amount: 20
```

**Comment by patrickpichler** [comment]
For this we should define something like an `overrideStrategy` flag which defines
what to do with the values. Otherwise it will always merge the values. 

The other question is, if it might make sense to split the value parameters into 
multiple parameter types such as `scalar`, `list`, `map`. Because some merge
strategies only make sense on some of those types.

**Comment by tatomir146** [comment]
Regarding `type: references`
You can reference to any type of properties, but it case you are referring to `type: value` it's not possible to reference subvalues. e.g.

```
...
    parameters:
      someMultiValues:
        type: value
        value:
          mike: lupus
          john: fabula

It is not allowed to map to the values of someMultiValues

    parameters:
      depParam:
        type: reference
        project: infrastructure
        api: alerting-profile
        config: some-config
        property: someMultiValues.mike
  
```
