### ISSUE TITLE
Duplicated ID's within configuration type should not be allowed

### ISSUE THREAD

**Issue by tatomir146** [Dynatrace/dynatrace-configuration-as-code#425]
This should not be possible and throw an error:

```
configs:
- id: myid
  config:
    name: Some Config
    template: my.json
- id: myid
  config:
    name: Another config
    template: my.json

```
