### ISSUE TITLE
Monaco 2.0 GA - Unable to use entity selector in scope

### ISSUE THREAD

**Issue by o-farooq** [Dynatrace/dynatrace-configuration-as-code#964]
**Describe the bug**
In Monaco 2.0.0-rc.4 I could use entity selector in scope , but in 2.0.0-rc.6+ and GA it throws a 404 error

**How to reproduce**

Sample Yaml config , have used simple entity selector for example

```
configs:
  - id: servicea-keyrequests
    type:
      settings:
        schema: builtin:settings.subscriptions.service
        schemaVersion: 0.1.7
        scope: '[{"type":"ENTITY_ID", "operator": "EQUALS", "value": "SERVICE-ABCD"}]' 
```

earlier it was creating keyrequest with the right scope , but now it complains with following error

` failed to deploy config cdx:builtin:settings.subscriptions.service:trader-core-keyrequests: failed to upsert dynatrace obj: failed to upsert config "servicea-keyrequests" after 3 retries: (HTTP 404)!
    Response was: {"error":{"code":404,"message":"Scope '[{\\\"type\\\":\\\"ENTITY_ID\\\", \\\"operator\\\": \\\"EQUALS\\\", \\\"value\\\": \\\"SERVICE-ABCD\\\"}]' not found"}} `

**Expected behavior**
Entity selector can be used in scope

**Log output**
` failed to deploy config cdx:builtin:settings.subscriptions.service:trader-core-keyrequests: failed to upsert dynatrace obj: failed to upsert config "servicea-keyrequests" after 3 retries: (HTTP 404)!
    Response was: {"error":{"code":404,"message":"Scope '[{\\\"type\\\":\\\"ENTITY_ID\\\", \\\"operator\\\": \\\"EQUALS\\\", \\\"value\\\": \\\"SERVICE-ABCD\\\"}]' not found"}} `

**Environment (please complete the following information):**
 - OS: Win 11 WSL
 - Tool version: 2.0.0 / 2.0.0-rc.6+
