### ISSUE TITLE
Config.yaml ID relevancy of Unique ID in Dynatrace

### ISSUE THREAD

**Issue by ZacBrumbaugh-KR** [Dynatrace/dynatrace-configuration-as-code#985]
**Describe the bug**
We are utilizing monaco V2 since last week and we have 2 clusters setup for high availability configured the same but in different regions. When utilizing Monaco v2, the ID in config.yaml seems to have more relevancy than the documentation suggests. The ID must be unique to create unique metric event alerts.

**How to reproduce**
1. Create a config.yaml with one alert
```
configs:
- id: foo
  type:
    api: anomaly-detection-metrics
  config:
    name: foo
    template: alert.json
    parameters:
      web_hook: <Injected_Environment_Value>
      region: <Injected_Environment_Value>
```

alert.json
```
"metricSelector": "some selector by cluster", 
"name": "Alert-{{ .region }} - {{ .web_hook }}", 
"description": "The {metricname} value was {alert_condition} normal behavior.", 
"severity": "CUSTOM_ALERT"
```

2. On each run of monaco (region 1 and region 2), make the name property unique in Anamoly detection metric event JSON

**Expected behavior**
When running monaco twice (one for each region) we should have two separate alerts, one for each region with corresponding alert names.

**Actual behavior**
The name of the alert is changed instead of a second alert being created.

**Comment by kbocock-krg** [comment]
Hi in the bug above and your suggestion to mitigate it could you please elaborate on the use of the config name property? When we get the json for anomaly detection it has a name field, but for some reason in Dynatrace UI the summary field has the json files name value. Very confusing. Another bug or as designed?

**Comment by warber** [comment]
This might be just the behavior of that endpoint. Whatever you have in the name field in JSON ends up as a summary in the UI. I can reproduce that on my DT environment. Note, that the "old" `anomaly-detection-metrics` API is replaced by the settings. So anomaly detection metrics events can also be created using the settings api (which I would strongly propose). The monaco CLI actually should also advise you to use the settings endpoint for it:
``` 
WARN  API for "anomaly-detection-metrics" is deprecated! Please consider migrating to "builtin:anomaly-detection.metric-events"!
```

you can take a look at how settings for anomaly detection metrics events look like just specifically downloading them from the environment e.g. using
```
monaco download --url  http://dt-url.com --token MONACO_TOKEN  --settings-schema builtin:anomaly-detection.metric-events
``` 
and use that instead.

**Comment by kbocock-krg** [comment]
Hi @warber  when I run the command above with schema I get over 200 config downloads. This does not seem to be what I want. Currently we are downloading our configuration by entity using the docs [here ](https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/anomaly-detection-api/anomaly-detection-api-applications/get-config). Curious about the v1 in the api. Could you please share a clean example of using the settings-schema in monaco config.yaml with a corresponding .json for a metric event?

**Comment by warber** [comment]
Hi,

> Ex. - We have no idea what we need for scope array. Type? etc.

This is why I've proposed to download a the corresponding settings objects via the `monaco download ...` command to have kind of an idea how the config for the corresponding settings schema looks like.


> Could you please share a clean example of using the settings-schema in monaco config.yaml with a corresponding .json for a metric event?

Sure, the following is a minimal example of a metric event created with the settings 2.0 API:

config.yaml
```yaml
configs:
- id: my-metric-event
  config:
    name: this-field-does-not-matter-for-settings
    template: metric-event.json
    skip: false
  type:
    settings:
      schema: builtin:anomaly-detection.metric-events
      schemaVersion: 1.0.14
      scope: environment

``` 

json template:
``` yaml
{
  "enabled": true,
  "summary": "My-metric-event",
  "queryDefinition": {
    "type": "METRIC_SELECTOR",
    "metricSelector": "builtin:apps.custom.reportedErrorCount"
  },
  "modelProperties": {
    "type": "STATIC_THRESHOLD",
    "threshold": 1.0,
    "alertOnNoData": false,
    "alertCondition": "ABOVE",
    "violatingSamples": 3,
    "samples": 5,
    "dealertingSamples": 5
  },
  "eventTemplate": {
    "title": "ad",
    "description": "The {metricname} value was {alert_condition} normal behavior.",
    "eventType": "CUSTOM_ALERT",
    "davisMerge": true,
    "metadata": []
  }
}

```
